<?php
/**
 * Source for the small edge proxy that mounts the Hatch frontend on the
 * site's own domain.
 *
 * The frontend Worker lives on a workers.dev address. When the site owner
 * wants it under their own domain (the whole domain, or a subfolder such as
 * /blog) Hatch deploys this proxy on a Workers route in their zone. The
 * proxy forwards matching requests to the frontend Worker and rewrites the
 * few places where the workers.dev address would leak into the page:
 * canonical and Open Graph URLs, and redirect Location headers.
 *
 * @package Hatch
 * @since   1.0.0
 */

defined( 'ABSPATH' ) || exit;

/**
 * Proxy Worker source generator.
 */
final class Hatch_Cloudflare_Proxy_Worker {

	/**
	 * Keep only "/segment/segment" characters, one leading slash, no trailing slash.
	 *
	 * @param string $raw User supplied path.
	 * @return string Path, "/blog" when the input is empty or the root.
	 */
	public static function normalize_subpath( string $raw ): string {
		$path = trim( $raw );
		$path = preg_replace( '#[^a-zA-Z0-9/_-]#', '', $path );
		$path = '/' . trim( (string) $path, '/' );
		return '/' === $path ? '/blog' : $path;
	}

	/**
	 * Whitelist the mount mode.
	 *
	 * @param string $raw User supplied mode.
	 * @return string "root" or "subfolder".
	 */
	public static function normalize_mount_mode( string $raw ): string {
		return 'subfolder' === strtolower( trim( $raw ) ) ? 'subfolder' : 'root';
	}

	/**
	 * Build the module source.
	 *
	 * @param string $origin     Frontend Worker origin, for example https://hatch-example.acme.workers.dev.
	 * @param string $public_host Public host name the visitor sees.
	 * @param string $subpath    Path prefix in subfolder mode.
	 * @param string $mount_mode "root" or "subfolder".
	 * @return string JavaScript module source.
	 */
	public static function build( string $origin, string $public_host, string $subpath, string $mount_mode ): string {
		$source = <<<'JS'
// Hatch edge proxy. Generated by the Hatch plugin; redeploy from wp-admin to change it.
const ORIGIN = __HATCH_ORIGIN__;
const PUBLIC_HOST = __HATCH_HOST__;
const MOUNT_MODE = __HATCH_MODE__;
const SUBPATH = __HATCH_SUBPATH__;
const WORDPRESS_PATHS = ['/wp-admin', '/wp-login.php', '/wp-json', '/wp-cron.php', '/wp-content', '/wp-includes', '/xmlrpc.php'];

function isWordPressPath(pathname) {
  return WORDPRESS_PATHS.some((p) => pathname === p || pathname.startsWith(p + '/'));
}

function isMounted(pathname) {
  if (isWordPressPath(pathname)) return false;
  if (MOUNT_MODE === 'root') return true;
  return pathname === SUBPATH || pathname.startsWith(SUBPATH + '/');
}

function toPublic(value) {
  return typeof value === 'string' && value.startsWith(ORIGIN) ? 'https://' + PUBLIC_HOST + value.slice(ORIGIN.length) : value;
}

export default {
  async fetch(request) {
    const url = new URL(request.url);
    if (!isMounted(url.pathname)) {
      return fetch(request);
    }
    const target = new URL(url.pathname + url.search, ORIGIN);
    const headers = new Headers(request.headers);
    headers.set('X-Forwarded-Host', PUBLIC_HOST);
    const upstream = await fetch(target.toString(), {
      method: request.method,
      headers,
      body: request.method === 'GET' || request.method === 'HEAD' ? undefined : request.body,
      redirect: 'manual',
    });
    const response = new Response(upstream.body, upstream);
    const location = response.headers.get('Location');
    if (location) {
      response.headers.set('Location', toPublic(location));
    }
    if ((response.headers.get('Content-Type') || '').includes('text/html')) {
      return new HTMLRewriter()
        .on('link[rel="canonical"]', { element(el) { el.setAttribute('href', toPublic(el.getAttribute('href') || '')); } })
        .on('meta[property="og:url"]', { element(el) { el.setAttribute('content', toPublic(el.getAttribute('content') || '')); } })
        .transform(response);
    }
    return response;
  },
};
JS;
		return strtr(
			$source,
			array(
				'__HATCH_ORIGIN__'  => wp_json_encode( untrailingslashit( $origin ) ),
				'__HATCH_HOST__'    => wp_json_encode( $public_host ),
				'__HATCH_MODE__'    => wp_json_encode( self::normalize_mount_mode( $mount_mode ) ),
				'__HATCH_SUBPATH__' => wp_json_encode( self::normalize_subpath( $subpath ) ),
			)
		);
	}
}
